# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_HOSTNAME = "ipr-sshkey-spec"

Vagrant.configure(2) do |config|
  config.vm.define VAGRANT_HOSTNAME do |c|
    c.vm.hostname = VAGRANT_HOSTNAME
    c.vm.box = "centos7"
    c.vm.box_url = "https://f0fff3908f081cb6461b407be80daf97f07ac418.googledrive.com/host/0BwtuV7VyVTSkUG1PM3pCeDJ4dVE/centos7.box"

    c.vm.provider(:virtualbox){|v| v.functional_vboxsf = false }
  end
end
